server:
  port: 8292

spring:
  application:
    name: client

client:
  path-cloud: /Users/gpbu13275/Yandex.Disk.localized/zipGradle
  path-gradle: /Users/gpbu13275/.gradle
  un-zip-gradle: /Users/gpbu13275/Documents/unzipgradle
  zip-gradle: /Users/gpbu13275/Documents/zipgradle
  m2-path-cloud: /Users/gpbu13275/Yandex.Disk.localized/zipM2
  m2-path: /Users/gpbu13275/.m2
  un-zip-m2: /Users/gpbu13275/Documents/unzipm2
  zip-m2: /Users/gpbu13275/Documents/zipM2
